import { useEffect, useMemo, useState } from 'react'
import { useApp } from '../context/AppContext'
import { useRouter } from '../router/Router'
import { errorMessage } from '../services/api'
import UserManagement from './UserManagement'
import AdminWorksheets from './AdminWorksheets'
import AcademicManagement from './AcademicManagement'
import './AdminPanel.css'

const NAV = [
  ['dashboard', '▦', 'Dashboard'], ['users', '◎', 'Users'], ['roles', '◇', 'Roles & Permissions'],
  ['subscriptions', '◉', 'Subscriptions'], ['worksheets', '□', 'Worksheets'], ['subjects', '⌘', 'Subjects'],
  ['events', '◷', 'Events'], ['notifications', '●', 'Notifications'], ['reports', '△', 'Reports'],
  ['activity', '↗', 'Activity Log'], ['system', '⚙', 'System Information'],
]

function State({ loading, error, empty, retry }) {
  if (loading) return <div className="admin-state" role="status"><span className="admin-spinner"/>Loading administration data…</div>
  if (error) return <div className="admin-state error" role="alert"><strong>Unable to load this section</strong><p>{error}</p><button onClick={retry}>Try again</button></div>
  if (empty) return <div className="admin-state"><strong>Nothing to show yet</strong><p>Records will appear here when they become available.</p></div>
  return null
}

function Toast({ message, type = 'success', clear }) { return message && <div className={`admin-toast ${type}`} role={type === 'error' ? 'alert' : 'status'}><span>{message}</span><button onClick={clear} aria-label="Dismiss message">×</button></div> }

function Confirm({ title, text, danger, busy, close, confirm }) {
  useEffect(() => { const escape = (event) => event.key === 'Escape' && !busy && close(); window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape) }, [busy, close])
  return <div className="admin-modal-bg" onMouseDown={(event) => event.target === event.currentTarget && !busy && close()}><section className="admin-confirm" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">{title}</h2><p>{text}</p><footer><button onClick={close} disabled={busy}>Cancel</button><button className={danger ? 'danger' : 'primary'} onClick={confirm} disabled={busy}>{busy ? 'Working…' : 'Confirm'}</button></footer></section></div>
}

export default function AdminPanel({ initialSection = 'dashboard' }) {
  const { user } = useApp(); const { navigate } = useRouter()
  const [section, setSection] = useState(initialSection), [open, setOpen] = useState(false)
  useEffect(() => setSection(initialSection), [initialSection])
  const choose = (next) => { setSection(next); setOpen(false); navigate(`/admin${next === 'dashboard' ? '' : `/${next}`}`) }
  return <main className="super-admin">
    <button className="admin-menu-toggle" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="admin-sidebar">☰ Admin menu</button>
    {open && <button className="admin-sidebar-scrim" aria-label="Close admin menu" onClick={() => setOpen(false)}/>} 
    <aside id="admin-sidebar" className={open ? 'open' : ''}><div className="admin-brand"><span>E</span><div><strong>EduSphere</strong><small>Administration</small></div></div><nav aria-label="Admin panel">{NAV.map(([id, icon, label]) => <button key={id} className={section === id ? 'active' : ''} onClick={() => choose(id)}><span aria-hidden="true">{icon}</span>{label}</button>)}</nav><div className="admin-user"><span>{user?.name?.[0]}</span><div><strong>{user?.name}</strong><small>Administrator</small></div></div></aside>
    <div className="admin-workspace">
      {section === 'dashboard' && <Overview onNavigate={choose}/>} 
      {section === 'users' && <UserManagement/>}
      {section === 'roles' && <Roles/>}
      {section === 'subscriptions' && <Subscriptions/>}
      {section === 'worksheets' && <AdminWorksheets/>}
      {section === 'subjects' && <AcademicManagement section="subjects"/>}
      {section === 'events' && <Events/>}
      {section === 'notifications' && <Notifications/>}
      {section === 'reports' && <Reports/>}
      {section === 'activity' && <ActivityLog/>}
      {section === 'system' && <SystemInfo/>}
    </div>
  </main>
}

function Overview({ onNavigate }) {
  const { api } = useApp(); const [data, setData] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [refresh, setRefresh] = useState(0)
  useEffect(() => { let live = true; setLoading(true); api.get('/admin/overview').then(({ data }) => live && setData(data)).catch((e) => live && setError(errorMessage(e))).finally(() => live && setLoading(false)); return () => { live = false } }, [api, refresh])
  if (loading || error) return <State loading={loading} error={error} retry={() => setRefresh((x) => x + 1)}/>
  const cards = [['users','Total users'],['active_users','Active users'],['suspended_users','Suspended'],['teachers','Teachers'],['students','Students'],['worksheets','Worksheets'],['published_worksheets','Published'],['draft_worksheets','Drafts'],['subjects','Subjects'],['events','Events'],['active_subscriptions','Active subscriptions'],['pending_subscriptions','Pending requests']]
  return <div className="admin-page"><PageHead eyebrow="Administration overview" title="Dashboard" text="A live view of people, content, subscriptions, and actions across EduSphere."/><section className="admin-metric-grid">{cards.map(([key,label],i)=><article key={key} className={`tone-${i%4}`}><span>{['◎','✓','!','△'][i%4]}</span><div><strong>{data.counts[key] ?? 0}</strong><small>{label}</small></div></article>)}</section><div className="admin-dashboard-grid"><Panel title="Pending actions"><div className="pending-list">{data.pending_actions.map(item=><button key={item.label} onClick={()=>onNavigate(item.section)}><span>{item.label}</span><strong>{item.count}</strong></button>)}</div></Panel><Panel title="Recently registered users"><MiniRows items={data.recent_users} primary="name" secondary="email" badge="role"/></Panel><Panel title="Recently uploaded worksheets"><MiniRows items={data.recent_worksheets} primary="title" secondary="subject" badge={(x)=>x.is_published?'Published':'Draft'}/></Panel><Panel title="Recent subscription activity"><MiniRows items={data.recent_subscriptions} primary="user_name" secondary="plan_name" badge="status"/></Panel><Panel title="Recent admin activity" wide><ActivityRows items={data.recent_activity}/></Panel><Panel title="Admin alerts" wide><NotificationRows items={data.alerts}/></Panel></div></div>
}
function PageHead({ eyebrow, title, text, action }) { return <header className="admin-page-head"><div><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action}</header> }
function Panel({ title, children, wide }) { return <section className={`admin-panel-card${wide?' wide':''}`}><h2>{title}</h2>{children}</section> }
function MiniRows({ items=[], primary, secondary, badge }) { return items.length ? <div className="mini-rows">{items.map((item,i)=><div key={item.id||i}><span className="mini-avatar">{String(item[primary]||'?')[0]}</span><div><strong>{item[primary]}</strong><small>{item[secondary]}</small></div><em>{typeof badge==='function'?badge(item):item[badge]}</em></div>)}</div>:<p className="muted">No recent records.</p> }
function ActivityRows({ items=[] }) { return items.length?<div className="activity-rows">{items.map(item=><div key={item.id}><span>↗</span><div><strong>{String(item.action).replaceAll('.',' ')}</strong><small>{item.actor_name||'System'} · {item.target_label||item.target_type||'LMS'}</small></div><time>{new Date(item.created_at).toLocaleString()}</time></div>)}</div>:<p className="muted">No admin activity recorded yet.</p> }
function NotificationRows({ items=[] }) { return items.length?<div className="activity-rows">{items.map(item=>{let body=item.data;try{body=typeof body==='string'?JSON.parse(body):body}catch{}return <div key={item.id}><span>●</span><div><strong>{body?.title||String(item.type).split('\\').pop()}</strong><small>{body?.message||'Administration notification'}</small></div><time>{new Date(item.created_at).toLocaleString()}</time></div>})}</div>:<p className="muted">No alerts right now.</p> }

function Roles() {
  const { api }=useApp(); const [roles,setRoles]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(null),[draft,setDraft]=useState({})
  const load=()=>{setLoading(true);setError('');api.get('/admin/roles').then(({data})=>{setRoles(data);setDraft(Object.fromEntries(data.map(r=>[r.id,r.permissions.map(p=>p.id)])))}).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))};useEffect(load,[api])
  const permissions=useMemo(()=>{const map=new Map();roles.flatMap(r=>r.permissions).forEach(p=>map.set(p.id,p));return [...map.values()]},[roles])
  const save=async role=>{setSaving(role.id);setError('');try{await api.put(`/admin/roles/${role.id}/permissions`,{permission_ids:draft[role.id]||[]});setNotice(`${role.name} permissions updated.`);load()}catch(e){setError(errorMessage(e))}finally{setSaving(null)}}
  return <div className="admin-page"><PageHead eyebrow="Access control" title="Roles & Permissions" text="Review each system role and control the permissions already defined by EduSphere."/><Toast message={notice} clear={()=>setNotice('')}/><Toast message={error} type="error" clear={()=>setError('')}/><State loading={loading} error="" empty={!roles.length}/>{!loading&&<section className="role-grid">{roles.map(role=><article key={role.id}><header><div><h2>{role.name}</h2><span>{role.users_count} users</span></div><em>{role.is_system?'System role':'Custom role'}</em></header><div className="permission-list">{permissions.map(p=><label key={p.id}><input type="checkbox" checked={(draft[role.id]||[]).includes(p.id)} onChange={e=>setDraft({...draft,[role.id]:e.target.checked?[...(draft[role.id]||[]),p.id]:(draft[role.id]||[]).filter(id=>id!==p.id)})}/><span><strong>{p.name}</strong><small>{p.group} · {p.description}</small></span></label>)}</div><button className="admin-primary" onClick={()=>save(role)} disabled={saving===role.id}>{saving===role.id?'Saving…':'Save permissions'}</button></article>)}</section>}</div>
}

function Subscriptions(){const{api}=useApp();const[tab,setTab]=useState('subscriptions'),[items,setItems]=useState([]),[meta,setMeta]=useState({}),[page,setPage]=useState(1),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState(null),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0)
  useEffect(()=>{let live=true;setLoading(true);const params=new URLSearchParams({page});if(query)params.set('q',query);if(status&&tab==='subscriptions')params.set('status',status);api.get(`/admin/${tab==='requests'?'subscription-requests':'subscriptions'}?${params}`).then(({data})=>{if(live){setItems(data.data||[]);setMeta(data)}}).catch(e=>live&&setError(errorMessage(e))).finally(()=>live&&setLoading(false));return()=>{live=false}},[api,page,query,status,tab,refresh])
  const act=async()=>{setBusy(true);setError('');try{if(pending.kind==='request')await api.patch(`/admin/subscription-requests/${pending.item.id}`,{action:pending.action});else await api.patch(`/admin/subscriptions/${pending.item.id}`,{action:pending.action,days:pending.days||30});setNotice(`Subscription ${pending.action} completed.`);setPending(null);setRefresh(x=>x+1)}catch(e){setError(errorMessage(e));setPending(null)}finally{setBusy(false)}}
  return <div className="admin-page"><PageHead eyebrow="Plans & access" title="Subscriptions" text="Process plan requests and manage real subscription access without exposing payment controls."/><Toast message={notice} clear={()=>setNotice('')}/><Toast message={error} type="error" clear={()=>setError('')}/><div className="admin-subtabs"><button className={tab==='subscriptions'?'active':''} onClick={()=>{setTab('subscriptions');setPage(1)}}>Subscriptions</button><button className={tab==='requests'?'active':''} onClick={()=>{setTab('requests');setPage(1)}}>Requests</button></div><Toolbar query={query} setQuery={v=>{setQuery(v);setPage(1)}} status={tab==='subscriptions'?status:null} setStatus={v=>{setStatus(v);setPage(1)}} statuses={['active','pending','expired','cancelled','rejected']}/><State loading={loading} empty={!loading&&!items.length}/>{!loading&&items.length>0&&<div className="admin-table-wrap"><table><thead><tr><th>User</th><th>Plan</th><th>Status</th><th>Dates</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td data-label="User"><strong>{item.user_name}</strong><small>{item.user_email}</small></td><td data-label="Plan">{item.plan_name}<small>{item.currency} {(item.price_cents/100).toFixed(2)}/{item.interval}</small></td><td data-label="Status"><Badge value={item.status}/></td><td data-label="Dates"><small>{item.starts_at?new Date(item.starts_at).toLocaleDateString():'Not started'} → {item.ends_at?new Date(item.ends_at).toLocaleDateString():'—'}</small></td><td data-label="Actions"><div className="table-actions">{tab==='requests'?<><button onClick={()=>setPending({kind:'request',action:'approve',item})}>Approve</button><button className="danger-lite" onClick={()=>setPending({kind:'request',action:'reject',item})}>Reject</button></>:<><button onClick={()=>setPending({kind:'subscription',action:item.status==='active'?'extend':'activate',item,days:30})}>{item.status==='active'?'Extend 30 days':'Activate'}</button><button className="danger-lite" onClick={()=>setPending({kind:'subscription',action:'cancel',item})}>Cancel</button></>}</div></td></tr>)}</tbody></table></div>}<Pager meta={meta} page={page} setPage={setPage}/>{pending&&<Confirm title={`Confirm subscription ${pending.action}`} text={`Apply “${pending.action}” to ${pending.item.user_name}'s ${pending.item.plan_name} ${pending.kind==='request'?'request':'subscription'}?`} danger={['reject','cancel','expire'].includes(pending.action)} busy={busy} close={()=>setPending(null)} confirm={act}/>}</div>}

function Events(){const{api}=useApp();const[items,setItems]=useState([]),[meta,setMeta]=useState({}),[page,setPage]=useState(1),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState(null),[removing,setRemoving]=useState(null),[refresh,setRefresh]=useState(0)
 const loadKey=`${page}|${query}|${status}|${refresh}`;useEffect(()=>{let live=true;setLoading(true);const p=new URLSearchParams({page});if(query)p.set('q',query);if(status)p.set('status',status);api.get(`/admin/events?${p}`).then(({data})=>{if(live){setItems(data.data||[]);setMeta(data)}}).catch(e=>live&&setError(errorMessage(e))).finally(()=>live&&setLoading(false));return()=>{live=false}},[api,loadKey]);const done=m=>{setNotice(m);setEditing(null);setRefresh(x=>x+1)};const remove=async()=>{try{await api.delete(`/admin/events/${removing.id}`);setRemoving(null);done('Event deleted.')}catch(e){setError(errorMessage(e));setRemoving(null)}}
 return <div className="admin-page"><PageHead eyebrow="Calendar content" title="Events" text="Create, schedule, publish and maintain LMS calendar events." action={<button className="admin-primary" onClick={()=>setEditing({})}>＋ Add event</button>}/><Toast message={notice} clear={()=>setNotice('')}/><Toast message={error} type="error" clear={()=>setError('')}/><Toolbar query={query} setQuery={v=>{setQuery(v);setPage(1)}} status={status} setStatus={v=>{setStatus(v);setPage(1)}} statuses={['scheduled','completed','cancelled']}/><State loading={loading} empty={!loading&&!items.length}/>{!loading&&items.length>0&&<div className="admin-table-wrap"><table><thead><tr><th>Event</th><th>Type</th><th>Date</th><th>Status</th><th>Creator</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td data-label="Event"><strong>{item.title}</strong><small>{item.class_name||'All LMS'}</small></td><td data-label="Type">{item.event_type}</td><td data-label="Date">{new Date(item.starts_at).toLocaleString()}</td><td data-label="Status"><Badge value={item.is_published?item.status:'draft'}/></td><td data-label="Creator">{item.creator_name}</td><td><div className="table-actions"><button onClick={()=>setEditing(item)}>Edit</button><button className="danger-lite" onClick={()=>setRemoving(item)}>Delete</button></div></td></tr>)}</tbody></table></div>}<Pager meta={meta} page={page} setPage={setPage}/>{editing&&<EventForm item={editing} api={api} close={()=>setEditing(null)} done={()=>done(editing.id?'Event updated.':'Event created.')}/>} {removing&&<Confirm title="Delete event" text={`Delete “${removing.title}”? This cannot be undone.`} danger close={()=>setRemoving(null)} confirm={remove}/>}</div>}
function EventForm({item,api,close,done}){const[form,setForm]=useState({title:item.title||'',description:item.description||'',event_type:item.event_type||'event',starts_at:item.starts_at?String(item.starts_at).slice(0,16):'',ends_at:item.ends_at?String(item.ends_at).slice(0,16):'',status:item.status||'scheduled',is_published:item.is_published??true}),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async e=>{e.preventDefault();setBusy(true);try{item.id?await api.patch(`/admin/events/${item.id}`,form):await api.post('/admin/events',form);done()}catch(x){setError(errorMessage(x))}finally{setBusy(false)}};return <div className="admin-modal-bg"><section className="admin-form-modal" role="dialog" aria-modal="true"><header><h2>{item.id?'Edit event':'Add event'}</h2><button onClick={close}>×</button></header><form onSubmit={submit}>{error&&<p className="form-error">{error}</p>}<label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-two"><label>Type<select value={form.event_type} onChange={e=>setForm({...form,event_type:e.target.value})}>{['event','class','assignment','deadline'].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['scheduled','completed','cancelled'].map(x=><option key={x}>{x}</option>)}</select></label><label>Starts<input type="datetime-local" required value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label>Ends<input type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></label></div><label className="check"><input type="checkbox" checked={form.is_published} onChange={e=>setForm({...form,is_published:e.target.checked})}/> Published</label><footer><button type="button" onClick={close}>Cancel</button><button className="admin-primary" disabled={busy}>{busy?'Saving…':'Save event'}</button></footer></form></section></div>}

function Notifications(){const{api}=useApp();const[items,setItems]=useState([]),[meta,setMeta]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[page,setPage]=useState(1),[refresh,setRefresh]=useState(0);useEffect(()=>{setLoading(true);api.get(`/notifications?page=${page}`).then(({data})=>{setItems(data.data||[]);setMeta(data)}).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))},[api,page,refresh]);const read=async id=>{try{await api.patch(`/notifications/${id}/read`);setRefresh(x=>x+1)}catch(e){setError(errorMessage(e))}};return <div className="admin-page"><PageHead eyebrow="Alerts" title="Notifications" text="Review system and account alerts delivered to your administrator account."/><Toast message={error} type="error" clear={()=>setError('')}/><State loading={loading} empty={!loading&&!items.length}/>{!loading&&<section className="notification-center"><NotificationRows items={items}/>{items.map(item=>!item.read_at&&<button key={`r${item.id}`} onClick={()=>read(item.id)}>Mark “{(()=>{try{return JSON.parse(item.data).title}catch{return 'notification'}})()}” read</button>)}</section>}<Pager meta={meta} page={page} setPage={setPage}/></div>}
function Reports(){const{api}=useApp();const[data,setData]=useState({reviews:[],reports:[]}),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{Promise.all([api.get('/reviews'),api.get('/performance-reports')]).then(([a,b])=>setData({reviews:a.data.data||a.data||[],reports:b.data.data||b.data||[]})).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))},[api]);return <div className="admin-page"><PageHead eyebrow="Oversight" title="Reports & Reviews" text="Read-only oversight of existing teacher reviews and learner performance reports."/><State loading={loading} error={error} empty={!loading&&!data.reviews.length&&!data.reports.length}/>{!loading&&<div className="admin-dashboard-grid"><Panel title="Teacher reviews"><MiniRows items={data.reviews} primary="status" secondary="remarks" badge={(x)=>x.percentage?`${x.percentage}%`:x.status}/></Panel><Panel title="Performance reports"><MiniRows items={data.reports} primary="overall_grade" secondary="teacher_comment" badge={(x)=>`${x.progress}%`}/></Panel></div>}</div>}
function ActivityLog(){const{api}=useApp();const[items,setItems]=useState([]),[meta,setMeta]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[page,setPage]=useState(1);useEffect(()=>{setLoading(true);api.get(`/admin/audit-logs?page=${page}`).then(({data})=>{setItems(data.data||[]);setMeta(data)}).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))},[api,page]);return <div className="admin-page"><PageHead eyebrow="Accountability" title="Admin Activity Log" text="A timestamped record of sensitive administrative changes."/><State loading={loading} error={error} empty={!loading&&!items.length}/>{!loading&&<Panel title="Recorded actions"><ActivityRows items={items}/></Panel>}<Pager meta={meta} page={page} setPage={setPage}/></div>}
function SystemInfo(){const{api}=useApp();const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{api.get('/admin/system').then(r=>setData(r.data)).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))},[api]);return <div className="admin-page"><PageHead eyebrow="Safe diagnostics" title="System Information" text="Read-only health and usage information. Secrets and infrastructure controls are never exposed."/><State loading={loading} error={error}/>{data&&<><section className="system-health"><span>✓</span><div><h2>System {data.status}</h2><p>Checked {new Date(data.checked_at).toLocaleString()}</p></div></section><div className="system-grid"><Panel title="Application"><dl><div><dt>Name</dt><dd>{data.application}</dd></div><div><dt>Environment</dt><dd>{data.environment}</dd></div><div><dt>Laravel</dt><dd>{data.framework}</dd></div><div><dt>PHP</dt><dd>{data.php}</dd></div><div><dt>Database</dt><dd>{data.database}</dd></div></dl></Panel><Panel title="Database totals"><dl>{Object.entries(data.counts).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{v}</dd></div>)}</dl></Panel><Panel title="Worksheet storage"><dl><div><dt>Files</dt><dd>{data.storage.worksheet_files}</dd></div><div><dt>Size</dt><dd>{(data.storage.worksheet_bytes/1024/1024).toFixed(2)} MB</dd></div></dl></Panel></div></>}</div>}
function Toolbar({query,setQuery,status,setStatus,statuses=[]}){return <div className="admin-toolbar"><label><span>⌕</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search…" aria-label="Search records"/></label>{status!==null&&<select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter by status"><option value="">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select>}</div>}
function Badge({value}){return <span className={`admin-badge ${value}`}>{String(value||'unknown').replaceAll('_',' ')}</span>}
function Pager({meta,page,setPage}){return meta?.last_page>1&&<nav className="admin-pager" aria-label="Pagination"><span>Page {meta.current_page} of {meta.last_page} · {meta.total} records</span><div><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><button disabled={page>=meta.last_page} onClick={()=>setPage(page+1)}>Next</button></div></nav>}
